# Generated by Django 6.0.5 on 2026-05-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='stage',
        ),
    ]
