"""Add admin_file field to Deliverable

Generated by code assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0005_add_missing_deliverables'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='admin_file',
            field=models.FileField(blank=True, null=True, upload_to='deliverable_admins/'),
        ),
    ]
