# Generated by Django 6.0.1 on 2026-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0006_add_admin_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readiness',
            name='level',
        ),
        migrations.AddField(
            model_name='readiness',
            name='admin_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readiness',
            name='incubatee_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
