# Generated by Django 6.0.1 on 2026-03-10 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0007_remove_readiness_level_readiness_admin_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='admin_file',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='upload_file',
        ),
        migrations.CreateModel(
            name='DeliverableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deliverables/')),
                ('uploaded_by_role', models.CharField(choices=[('admin', 'Admin'), ('incubatee', 'Incubatee')], max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='incubator.deliverable')),
            ],
        ),
    ]
