# Generated by Django 6.0.1 on 2026-03-11 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('milestone_progress', models.IntegerField(help_text='Order or index of the milestone')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('tl', 'Tagalog')], default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='DeliverableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('milestone_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_templates', to='incubator.milestonetemplate')),
            ],
        ),
    ]
