# Generated by Django 6.0.1 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0010_milestonetemplate_user_preferred_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog')], default='en', max_length=10),
        ),
    ]
