# Generated by Django 6.0.1 on 2026-03-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0011_alter_user_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
    ]
