# Generated by Django 6.0.1 on 2026-03-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0012_remove_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incubator.deliverabletemplate'),
        ),
        migrations.AddField(
            model_name='deliverabletemplate',
            name='admin_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_templates/'),
        ),
    ]
