# Generated by Django 6.0.1 on 2026-03-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0013_deliverable_template_deliverabletemplate_admin_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
