# Generated by Django 6.0.1 on 2026-03-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0015_adminprofile_incubateeprofile'),
    ]

    operations = [
    ]
