# Generated by Django 6.0.5 on 2026-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0016_create_initial_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., Status 1', max_length=200)),
                ('text', models.CharField(help_text='Text of the status update', max_length=500)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incubateeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='IncubateeProfile',
        ),
    ]
