# Generated by Django 6.0.5 on 2026-05-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0018_cohort_startup_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverablefile',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliverablefile',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverablefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='deliverables/'),
        ),
    ]
