# Generated by Django 6.0.5 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0019_deliverablefile_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverabletemplate',
            name='admin_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
