# Generated by Django 6.0.5 on 2026-05-18 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0020_deliverabletemplate_admin_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableTemplateResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='admin_templates/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='incubator.deliverabletemplate')),
            ],
        ),
    ]
