# Generated by Django 6.0.5 on 2026-05-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0021_deliverabletemplateresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverablefile',
            name='link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliverabletemplate',
            name='admin_link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliverabletemplateresource',
            name='link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
